export const PB_LOAD_HOME = 'PB_LOAD_HOME';
export const PB_LOAD_HOME_SUCCESS = 'PB_LOAD_HOME_SUCCESS';
export const PB_LOAD_HOME_ERROR = 'PB_LOAD_HOME_ERROR';

export const PB_LOAD_CAMPAIGNS = 'PB_LOAD_CAMPAIGNS';
export const PB_LOAD_CAMPAIGNS_SUCCESS = 'PB_LOAD_CAMPAIGNS_SUCCESS';
export const PB_LOAD_CAMPAIGNS_ERROR = 'PB_LOAD_CAMPAIGNS_ERROR';

export const PB_LOAD_CAMPAIGN = 'PB_LOAD_CAMPAIGN';
export const PB_LOAD_CAMPAIGN_SUCCESS = 'PB_LOAD_CAMPAIGN_SUCCESS';
export const PB_LOAD_CAMPAIGN_ERROR = 'PB_LOAD_CAMPAIGN_ERROR';

export const PB_LOAD_CATEGORY = 'PB_LOAD_CATEGORY';
export const PB_LOAD_CATEGORY_SUCCESS = 'PB_LOAD_CATEGORY_SUCCESS';
export const PB_LOAD_CATEGORY_ERROR = 'PB_LOAD_CATEGORY_ERROR';

export const PB_LOAD_PLAN = 'PB_LOAD_PLAN';
export const PB_LOAD_PLAN_SUCCESS = 'PB_LOAD_PLAN_SUCCESS';
export const PB_LOAD_PLAN_ERROR = 'PB_LOAD_PLAN_ERROR';

export const PB_LOAD_TRANSLATIONS = 'PB_LOAD_TRANSLATIONS';
export const PB_LOAD_TRANSLATIONS_SUCCESS = 'PB_LOAD_TRANSLATIONS_SUCCESS';
export const PB_LOAD_TRANSLATIONS_ERROR = 'PB_LOAD_TRANSLATIONS_ERROR';

export const PB_LOAD_LANGUAGES = 'PB_LOAD_LANGUAGES';
export const PB_LOAD_LANGUAGES_SUCCESS = 'PB_LOAD_LANGUAGES_SUCCESS';
export const PB_LOAD_LANGUAGES_ERROR = 'PB_LOAD_LANGUAGES_ERROR';

export const PLANS_ADD_PLAN = 'PLANS_ADD_PLAN';
export const PLANS_ADD_PLAN_SUCCESS = 'PLANS_ADD_PLAN_SUCCESS';
export const PLANS_ADD_PLAN_ERROR = 'PLANS_ADD_PLAN_ERROR';

export const PLANS_ACCEPT_INVITE = 'PLANS_ACCEPT_INVITE';
export const PLANS_ACCEPT_INVITE_SUCCESS = 'PLANS_ACCEPT_INVITE_SUCCESS';
export const PLANS_ACCEPT_INVITE_ERROR = 'PLANS_ACCEPT_INVITE_ERROR';

export const PLANS_LOAD_PLANS = 'PLANS_LOAD_PLANS';
export const PLANS_LOAD_PLANS_SUCCESS = 'PLANS_LOAD_PLANS_SUCCESS';
export const PLANS_LOAD_PLANS_ERROR = 'PLANS_LOAD_PLANS_ERROR';

export const PLANS_LOAD_PLAN_CONTENT = 'PLANS_LOAD_PLAN_CONTENT';
export const PLANS_LOAD_PLAN_CONTENT_SUCCESS =
  'PLANS_LOAD_PLAN_CONTENT_SUCCESS';
export const PLANS_LOAD_PLAN_CONTENT_ERROR = 'PLANS_LOAD_PLAN_CONTENT_ERROR';

export const PLANS_SET_READING_STEP = 'PLANS_SET_READING_STEP';

export const PLANS_MARK_AS_READ = 'PLANS_MARK_AS_READ';
export const PLANS_MARK_AS_READ_SUCCESS = 'PLANS_MARK_AS_READ_SUCCESS';
export const PLANS_MARK_AS_READ_ERROR = 'PLANS_MARK_AS_READ_ERROR';

export const PLANS_LOAD_ARCHIVED_PLANS = 'PLANS_LOAD_ARCHIVED_PLANS';
export const PLANS_LOAD_ARCHIVED_PLANS_SUCCESS =
  'PLANS_LOAD_ARCHIVED_PLANS_SUCCESS';
export const PLANS_LOAD_ARCHIVED_PLANS_ERROR =
  'PLANS_LOAD_ARCHIVED_PLANS_ERROR';

export const PLANS_ARCHIVE_PLAN = 'PLANS_ARCHIVE_PLAN';
export const PLANS_ARCHIVE_PLAN_SUCCESS = 'PLANS_ARCHIVE_PLAN_SUCCESS';
export const PLANS_ARCHIVE_PLAN_ERROR = 'PLANS_ARCHIVE_PLAN_ERROR';

export const PLANS_REMOVE_ARCHIVED_PLAN = 'PLANS_REMOVE_ARCHIVED_PLAN';
export const PLANS_REMOVE_ARCHIVED_PLAN_SUCCESS =
  'PLANS_REMOVE_ARCHIVED_PLAN_SUCCESS';
export const PLANS_REMOVE_ARCHIVED_PLAN_ERROR =
  'PLANS_REMOVE_ARCHIVED_PLAN_ERROR';

export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_ERROR = 'PROFILE_LOAD_ERROR';

export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';

export const PROFILE_REQUEST_CODE = 'PROFILE_REQUEST_CODE';
export const PROFILE_REQUEST_CODE_SUCCESS = 'PROFILE_REQUEST_CODE_SUCCESS';
export const PROFILE_REQUEST_CODE_ERROR = 'PROFILE_REQUEST_CODE_ERROR';

export const PROFILE_VERIFY_CODE = 'PROFILE_VERIFY_CODE';
export const PROFILE_VERIFY_CODE_SUCCESS = 'PROFILE_VERIFY_CODE_SUCCESS';
export const PROFILE_VERIFY_CODE_ERROR = 'PROFILE_VERIFY_CODE_ERROR';

export const PROFILE_GET_SIGNED_REQUEST = 'PROFILE_GET_SIGNED_REQUEST';
export const PROFILE_GET_SIGNED_REQUEST_SUCCESS =
  'PROFILE_GET_SIGNED_REQUEST_SUCCESS';
export const PROFILE_GET_SIGNED_REQUEST_ERROR =
  'PROFILE_GET_SIGNED_REQUEST_ERROR';

export const PROFILE_UPLOAD_IMAGE_COMPLETED = 'PROFILE_UPLOAD_IMAGE_COMPLETED';
export const PROFILE_UPLOAD_IMAGE_COMPLETED_SUCCESS =
  'PROFILE_UPLOAD_IMAGE_COMPLETED_SUCCESS';
export const PROFILE_UPLOAD_IMAGE_COMPLETED_ERROR =
  'PROFILE_UPLOAD_IMAGE_COMPLETED_ERROR';

export const PROFILE_IMAGE_NOT_UPLOADED = 'PROFILE_IMAGE_NOT_UPLOADED';

export const RESET_STORE = 'RESET_STORE';

export const SETTINGS_LOAD = 'SETTINGS_LOAD';
export const SETTINGS_LOAD_SUCCESS = 'SETTINGS_LOAD_SUCCESS';
export const SETTINGS_LOAD_ERROR = 'SETTINGS_LOAD_ERROR';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_ERROR = 'UPDATE_SETTINGS_ERROR';

export const COMMENTS_LOAD = 'COMMENTS_LOAD';
export const COMMENTS_LOAD_SUCCESS = 'COMMENTS_LOAD_SUCCESS';
export const COMMENTS_LOAD_ERROR = 'COMMENTS_LOAD_ERROR';

export const COMMENTS_POST_COMMENT = 'COMMENTS_POST_COMMENT';
export const COMMENTS_POST_COMMENT_SUCCESS = 'COMMENTS_POST_COMMENT_SUCCESS';
export const COMMENTS_POST_COMMENT_ERROR = 'COMMENTS_POST_COMMENT_ERROR';

export const SHOW_COMMENT_INPUT = 'SHOW_COMMENT_INPUT';
export const HIDE_COMMENT_INPUT = 'HIDE_COMMENT_INPUT';

export const NOTIFICATIONS_LOAD = 'NOTIFICATIONS_LOAD';
export const NOTIFICATIONS_LOAD_SUCCESS = 'NOTIFICATIONS_LOAD_SUCCESS';
export const NOTIFICATIONS_LOAD_ERROR = 'NOTIFICATIONS_LOAD_ERROR';
export const NOTIFICATIONS_BANNER_HIDE = 'NOTIFICATIONS_BANNER_HIDE';
export const NOTIFICATIONS_MARK_AS_READ = 'NOTIFICATIONS_MARK_AS_READ';
export const NOTIFICATIONS_MARK_AS_READ_SUCCESS =
  'NOTIFICATIONS_MARK_AS_READ_SUCCESS';
export const NOTIFICATIONS_MARK_AS_READ_ERROR =
  'NOTIFICATIONS_MARK_AS_READ_ERROR';

export const SET_FONT_SIZE = 'SET_FONT_SIZE';
export const SET_LINE_HEIGHT = 'SET_LINE_HEIGHT';

export const DONATION_LOAD_PRODUCTS = 'DONATION_LOAD_PRODUCTS';
export const DONATION_LOAD_PRODUCTS_SUCCESS = 'DONATION_LOAD_PRODUCTS_SUCCESS';
export const DONATION_LOAD_PRODUCTS_ERROR = 'DONATION_LOAD_PRODUCTS_ERROR';

export const DONATION_GET_SIGNED_LINK = 'DONATION_GET_SIGNED_LINK';
export const DONATION_GET_SIGNED_LINK_SUCCESS =
  'DONATION_GET_SIGNED_LINK_SUCCESS';
export const DONATION_GET_SIGNED_LINK_ERROR = 'DONATION_GET_SIGNED_LINK_ERROR';

export const SUBSCRIPTION_LOAD = 'SUBSCRIPTION_LOAD';
export const SUBSCRIPTION_LOAD_SUCCESS = 'SUBSCRIPTION_LOAD_SUCCESS';
export const SUBSCRIPTION_LOAD_ERROR = 'SUBSCRIPTION_LOAD_ERROR';

export const SUBSCRIPTION_RENEW = 'SUBSCRIPTION_RENEW';
export const SUBSCRIPTION_RENEW_SUCCESS = 'SUBSCRIPTION_RENEW_SUCCESS';
export const SUBSCRIPTION_RENEW_ERROR = 'SUBSCRIPTION_RENEW_ERROR';

export const SUBSCRIPTION_LOAD_PLANS = 'SUBSCRIPTION_LOAD_PLANS';
export const SUBSCRIPTION_LOAD_PLANS_SUCCESS =
  'SUBSCRIPTION_LOAD_PLANS_SUCCESS';
export const SUBSCRIPTION_LOAD_PLANS_ERROR = 'SUBSCRIPTION_LOAD_PLANS_ERROR';
